# This starter workflow is for a CMake project running on multiple platforms. There is a different starter workflow if you just want a single platform.
# See: https://github.com/actions/starter-workflows/blob/main/ci/cmake-single-platform.yml
name: Cross Compile

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  zig-build:
    runs-on: ubuntu-latest

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        target:
          - x86_64-linux-gnu
          - aarch64-linux-gnu
          - x86_64-windows-gnu
          - arm-linux-gnueabihf
          - aarch64-macos
        build_type: [Release]

    steps:
    - uses: actions/checkout@v5
    - uses: mlugg/setup-zig@a67e68dc5c8281d9608136d3d7ca1b282213e4ac
      with:
        version: 0.14.0

    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/cmake/zig.toolchain.${{ matrix.target }}
        -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
        -S ${{ github.workspace }}

    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

    - name: Achive build results
      uses: actions/upload-artifact@v5
      with:
        name: bennugd_libretro.${{ matrix.target }}.${{ matrix.build_type }}
        path: ${{ steps.strings.outputs.build-output-dir }}/bennugd_libretro*.*
  android-build:
    runs-on: ubuntu-latest
    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      matrix:
        abi:
          - arm64-v8a
          - armeabi-v7a
        build_type: [Release]

    steps:
    - uses: actions/checkout@v5
    - name: Set reusable strings
      # Turn repeated input strings (such as the build output directory) into step outputs. These step outputs can be used throughout the workflow file.
      id: strings
      shell: bash
      run: |
        echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: >
        cmake -B ${{ steps.strings.outputs.build-output-dir }}
        -DCMAKE_TOOLCHAIN_FILE=${ANDROID_NDK_ROOT}/build/cmake/android.toolchain.cmake
        -DCMAKE_BUILD_TYPE=Release
        -DANDROID_PLATFORM=18
        -DANDROID_ABI=${{ matrix.abi }}
        -DCMAKE_WARN_DEPRECATED=false
        -S ${{ github.workspace }}
    - name: Build
      # Build your program with the given configuration. Note that --config is needed because the default Windows generator is a multi-config generator (Visual Studio generator).
      run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}
    - name: Achive build results
      uses: actions/upload-artifact@v5
      with:
        name: bennugd_libretro.android-${{ matrix.abi }}.${{ matrix.build_type }}
        path: ${{ steps.strings.outputs.build-output-dir }}/bennugd_libretro*.*

  webos-build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        arch:
          - armv7
        build_type: [Release, Debug]

    env:
      WEBOS_SDK_URL: https://github.com/openlgtv/buildroot-nc4/releases/download/webos-a38c582/arm-webos-linux-gnueabi_sdk-buildroot-x86_64.tar.gz
      WEBOS_SDK_DIR: ${{ github.workspace }}/arm-webos-linux-gnueabi_sdk-buildroot

    steps:
      - uses: actions/checkout@v5

      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"

      - name: Install dependencies
        run: |
          sudo apt update -y
          sudo apt install -y wget bzip2 cmake file

      - name: Download and extract WebOS SDK
        run: |
          wget $WEBOS_SDK_URL
          tar xvfz $(basename $WEBOS_SDK_URL)
          rm $(basename $WEBOS_SDK_URL)

      - name: Relocate WebOS SDK
        run: |
          cd $WEBOS_SDK_DIR
          ./relocate-sdk.sh

      - name: Configure CMake
        run: >
          cmake
          -B ${{ steps.strings.outputs.build-output-dir }}
          -DCMAKE_TOOLCHAIN_FILE=${{ env.WEBOS_SDK_DIR }}/share/buildroot/toolchainfile.cmake
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }}
          -DCMAKE_C_FLAGS="-D__WEBOS__=1" \ 
          -S ${{ github.workspace }}

      - name: Build
        run: >
          cmake --build ${{ steps.strings.outputs.build-output-dir }} --config ${{ matrix.build_type }}

      - name: Inspect built file
        run: file ${{ steps.strings.outputs.build-output-dir }}/bennugd_libretro.so

      - name: Archive build results
        uses: actions/upload-artifact@v5
        with:
          name: bennugd_libretro.webos-${{ matrix.arch }}.${{ matrix.build_type }}
          path: |
            ${{ steps.strings.outputs.build-output-dir }}/bennugd_libretro.so

  master-branch-release:
    runs-on: ubuntu-latest
    needs: [zig-build,android-build]
    permissions:
      contents: write
    if: github.ref == 'refs/heads/master'
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - uses: actions/checkout@v5
    - name: delete previous release
      shell: bash
      run: |
        gh release delete mainline-latest --yes --cleanup-tag || true
    - name: download artifacts
      uses: actions/download-artifact@v6
    - name: compress artifacts
      shell: bash
      run: |
        for d in ./bennugd_libretro.*.*/ ; do (cd "$d" && tar czvf "../$(basename $d).tgz" .); done
    - name: create new release
      shell: bash
      run: |
        gh release create mainline-latest --latest=false --title "Mainline latest" --notes "Latest manline release" --target ${{ github.sha }} --prerelease=true ./bennugd_libretro.*.*.tgz
